FROM tensorflow/tensorflow:2.18.0rc1-gpu
LABEL Author="Ben Townsend, Madison May"

# tensorboard
EXPOSE 6006

RUN apt-get update && mkdir /Finetune
ADD requirements.txt /Finetune/requirements.txt
RUN pip3 install -r /Finetune/requirements.txt && \
    python3 -m spacy download en

WORKDIR /Finetune
COPY docker/bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc

CMD ["sleep", "infinity"]
