FROM tensorflow/tensorflow:2.8.0rc1
LABEL Author="Ben Townsend, Madison May"

# tensorboard
EXPOSE 6006

RUN apt-get update && mkdir /Finetune
ADD requirements.txt /Finetune/requirements.txt
RUN pip3 install -r /Finetune/requirements.txt && \
    python3 -m spacy download en

WORKDIR /Finetune
ADD . /Finetune
COPY docker/bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc
RUN python3 setup.py develop

CMD ["sleep","infinity"]
