import io
import logging
import math
import os
import pathlib
import random
import tempfile
import threading
import time
import typing as t
import warnings
import weakref
from abc import ABCMeta, abstractmethod
from copy import deepcopy
from datetime import datetime
from typing import Dict, List, Mapping, Tuple

import joblib
import numpy as np
import tensorflow as tf
from tensorflow.python.framework.ops import gradient_registry as tf_gradient_registry
from tensorflow.python.keras.backend import reset_uids as keras_reset_uids

from finetune.base_models.bert.roberta_encoder import RoBERTaEncoderV2
from finetune.config import assert_valid_config, get_default_config
from finetune.errors import FinetuneError
from finetune.input_pipeline import InputMode
from finetune.model import get_keras_model
from finetune.optimizers.learning_rate_schedules import FinetuneKerasLRSchedule
from finetune.saver import Saver
from finetune.util.download import download_data_if_required
from finetune.util.gpu_info import gpu_info
from finetune.util.timing import ProgressBar

LOGGER = logging.getLogger("finetune")


def issubclass_or_instance(a, b):
    try:
        return issubclass(a, b)
    except TypeError:
        return isinstance(a, b)


def start_end_gen(gen):
    """
    yields from generator along with booleans for start and end.
    """
    start = True
    previous = next(gen)
    for g in gen:
        yield previous, start, False
        previous = g
        start = False
    yield previous, start, True


class FinetuneRegistry:
    """
    Very thin global registry that tracks finetune models so that we can cleanup the keras session without breaking
    any models. When cleanup is called any models loaded in the GPU will be closed and the keras session will be cleared.
    """

    def __init__(self):
        self._refs = set()
        self._refs_lock = threading.RLock()

    def register(self, model: "BaseModel") -> None:
        def _finalizer(wr: weakref.ref) -> None:
            with self._refs_lock:
                self._refs.discard(wr)

        with self._refs_lock:
            self._refs.add(weakref.ref(model, _finalizer))

    def live_models(self) -> t.Iterator["BaseModel"]:
        """
        Iterate currently alive holder objects.
        """
        with self._refs_lock:
            for wr in tuple(self._refs):
                obj = wr()
                if obj is None:
                    self._refs.discard(wr)
                else:
                    yield obj

    def cleanup(self):
        """
        Close all live models and clear dead weakrefs, then clear the Keras session.
        """
        # There are other registries in the tensorflow.python.framework.ops that we can clear if we need to.
        tf_gradient_registry._registry = {
            k: v
            for k, v in tf_gradient_registry._registry.items()
            if not k.startswith("CustomGradient")
        }
        with self._refs_lock:
            for model in self.live_models():
                model.close()
        tf.keras.backend.clear_session()


MODEL_REGISTRY = FinetuneRegistry()


class BaseModel(object, metaclass=ABCMeta):
    """
    A sklearn-style task agnostic base class for finetuning a Transformer language model.
    """

    defaults = dict()

    def __init__(self, **kwargs):
        """
        For a full list of configuration options, see `finetune.config`.

        :param config: A config object generated by `finetune.config.get_config` or None (for default config).
        :param **kwargs: key-value pairs of config items to override.
        """

        # Finalizer runs at garbage collection and exit
        def _finalizer_func(ws_ref):
            try:
                ws = ws_ref()
                if ws is not None and hasattr(ws, "close"):
                    ws.close(update_saver=False)
            except ReferenceError:
                # Suppress "Weakly referenced object no longer exists"
                pass

        self_ref = weakref.ref(self)
        self._finalizer = weakref.finalize(
            self,
            _finalizer_func,
            self_ref,
        )
        self.config_overrides = deepcopy(self.defaults)
        self.config_overrides.update(kwargs)
        self.config = self.resolve_config()
        self.validate_config()
        download_data_if_required(self.config.base_model)
        self.input_pipeline = self._get_input_pipeline()
        self._trained = False
        self._initialize()
        if self.config.debugging_logs:
            os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"
        self.check_gpu_for_fp16()
        self._model = None

    def check_gpu_for_fp16(self):
        if not gpu_info()["fp16_inference"]:
            if self.config.float_16_predict or self.config.mixed_precision:
                LOGGER.warning(
                    "This GPU does not support float 16 ops but they were requested in the config. They are being turned off."
                )
                self.config = self.resolve_config(no_fp16=True)

    def resolve_config(self, no_fp16=False, **kwargs):
        self.config_overrides.update(kwargs)
        assert_valid_config(**self.config_overrides)
        config = get_default_config()
        config.base_model = kwargs.get("base_model", config.base_model)

        auto_keys = []
        config.update(self.config_overrides)
        for k, v in config.items():
            if isinstance(v, str) and v.lower() == "auto":
                auto_keys.append(k)
            elif k in self.config_overrides:
                continue
            elif k in config.base_model.settings:
                config[k] = config.base_model.settings[k]

        if no_fp16 and "fp16" in config.optimize_for:
            new_optimize_for = config.optimize_for.replace("_fp16", "")
            LOGGER.warning(
                "optimize_for was set to {} but fp16 is not supported by this gpu so falling back to {}".format(
                    config.optimize_for, new_optimize_for
                )
            )
            config.optimize_for = new_optimize_for

        overrides = config.base_model.get_optimal_params(config)
        for ak in auto_keys:
            if ak not in overrides:
                raise ValueError("There is no auto setting for {}".format(ak))
            config[ak] = overrides[ak]

        if hasattr(self, "input_pipeline"):
            self.input_pipeline.config = config

        if hasattr(self, "config"):
            for k, v in self.config.items():
                if k not in auto_keys and k != "optimize_for" and config[k] != v:
                    LOGGER.warning(
                        "Copying value {} for key {} from old config when reinitializing".format(
                            v, k
                        )
                    )
                    config[k] = v
        return config

    def validate_config(self):
        pass

    @abstractmethod
    def _get_input_pipeline(self):
        pass

    def _initialize(self):
        # Initializes the non-serialized bits of the class.
        self._set_random_seed(self.config.seed)
        self._model = None
        self.saver = Saver(
            fallback_filename=self.config.base_model_path,
            save_dtype=self.config.save_dtype,
            permit_uninitialized=self.config.permit_uninitialized,
        )
        MODEL_REGISTRY.register(self)

    @abstractmethod
    def target_block(self, *, config, n_outputs, **kwargs):
        # Overridden by subclass to attach a target model onto the shared base featurizer.
        raise NotImplementedError

    def _n_steps(self, n_examples, batch_size, n_gpus):
        # Floor because we do drop the final elements of each batch if they don't make up a full batch.
        steps = int(math.floor(n_examples / (batch_size * n_gpus)))
        return steps

    def finetune(
        self,
        Xs,
        Y,
        context=None,
        update_hook=None,
    ):
        zipped_data_list = self.input_pipeline.zip_list_to_dict(
            X=Xs, Y=Y, context=context
        )
        datasets = self.input_pipeline.get_dataset_from_list(
            zipped_data_list, input_mode=InputMode.TRAIN, update_hook=update_hook
        )

        steps_per_epoch = self._n_steps(
            n_examples=self.input_pipeline.dataset_size,
            batch_size=self.config.batch_size,
            n_gpus=1,
        )
        num_steps = steps_per_epoch * self.config.n_epochs
        self.model.compile(
            optimizer=tf.keras.optimizers.get(
                {
                    "class_name": self.config.optimizer,
                    "config": {
                        "learning_rate": FinetuneKerasLRSchedule(
                            schedule=self.config.lr_schedule,
                            base_lr=self.config.lr,
                            total_steps=num_steps,
                            warmup=self.config.lr_warmup,
                        ),
                        "weight_decay": self.config.l2_reg,
                        "beta_1": self.config.b1,
                        "beta_2": self.config.b2,
                        "epsilon": self.config.epsilon,
                        "clipnorm": self.config.max_grad_norm,
                        "gradient_accumulation_steps": self.config.accum_steps
                        if self.config.accum_steps > 1
                        else None,
                    },
                }
            ),
            jit_compile=self.config.base_model.supports_xla,  # We always Jit compile the train step as it is required for efficient use of the optimizers.
            auto_scale_loss=True,
            steps_per_execution=1,  # Performance impact of rolling this is minor and setting to 1 minimises compile times
        )
        exclude_from_l2 = []
        if not self.config.vector_l2:
            exclude_from_l2 += [v for v in self.model.variables if len(v.shape) <= 1]
        exclude_from_l2 += [
            v for v in self.model.variables if "Transition_matrix" not in v.name
        ]
        if exclude_from_l2:
            self.model.optimizer.exclude_from_weight_decay(exclude_from_l2)
        LOGGER.debug("Fitting model")
        # Because the dataset is already repeated n_epoch times, we need to pass steps_per_epoch to the fit method.
        train_dataset = datasets["train_dataset"]
        # logs = "logs/" + datetime.now().strftime("%Y%m%d-%H%M%S")
        # tf.profiler.experimental.start(logs)
        self.model.fit(
            train_dataset,
            epochs=self.config.n_epochs,
            steps_per_epoch=steps_per_epoch,
            # verbose=2 results in one line logged per epoch. These are not always intuitive
            # because their epoch numbers don't align with ours when we're using ANS.
            # However, for now it's nice to get signs of life from keras.
            # We have to disable it when there will only be a single step due to a bug in keras ProgBar
            verbose=2 if steps_per_epoch * self.config.n_epochs > 1 else 0,
        )
        # tf.profiler.experimental.stop()
        self._trained = True

    @property
    def model(self) -> tf.keras.Model:
        if self._model is None:
            # Keras holds a global state of layer names and anything without an explicit name gets a name with a
            # uid suffix. When multiple models are created in the same process these names can conflict causing issues
            # with saving and loading.
            # Reset Uids before and after build to keep the naming isolated.
            keras_reset_uids()
            # We either need to explictly handle the dtype policies in every layer or deal with this hack to set and unset
            # our desired policy. Setting dtype policy on the model does not seem to cascade to lower layers.
            initial_dtype_policy = tf.keras.config.dtype_policy()
            dtype_policy = "float32"
            if self.config.float_16_predict or self.config.mixed_precision:
                if self.config.version.split(".")[0] == "0":
                    # Assumption is if we're loading old float16 models we're not going to further train them.
                    dtype_policy = "float16"
                else:
                    # Just use mixed float16 going forwards.
                    dtype_policy = "mixed_float16"
            tf.keras.config.set_dtype_policy(dtype_policy)
            self._model = self._get_keras_model()
            # Does a symbolic first pass to build the model and give us variables we can initialize.
            # Keras does not have a post-build hook option because it can be run in eager and shapes are calculated alongside the first
            # call. Therefore we need to pass either a real tensor or this symbolic tensor to get variables.
            LOGGER.debug("Building model")
            self._model(
                self.input_pipeline.keras_input_def(
                    concrete_dims=False, include_targets=False
                )
            )
            self.saver.initialize_model(self._model)

            tf.keras.config.set_dtype_policy(initial_dtype_policy)
            keras_reset_uids()
            LOGGER.debug("Model built")
        return self._model

    def _get_keras_model(self):
        if self.input_pipeline.target_dim is None:
            target_block = None
        else:
            target_block = self.target_block(
                config=self.config,
                n_outputs=self.input_pipeline.target_dim,
            )
        model = get_keras_model(
            target_block=target_block,
            encoder=self.input_pipeline.text_encoder,
            target_dim=self.input_pipeline.target_dim,
            label_encoder=self.input_pipeline.label_encoder,
            config=self.config,
            train_input_signature=self.input_pipeline.keras_input_signature(
                concrete_dims=True, include_targets=True
            ),
            predict_input_signature=self.input_pipeline.keras_input_signature(
                concrete_dims=False, include_targets=False
            ),
            use_xla=self.config.xla,
        )
        return model

    def _sort_by_length(
        self, zipped_text: List[Dict[str, str]]
    ) -> Tuple[List[Dict[str, str]], np.ndarray]:
        """
        Given a list of dictionaries from "X" to text of a document, sort the list
        by the length of each element in the zipped_text

        Args:
            zipped_text: {"X": <text>} for each document in a dataset

        Returns:
            sorted_text: zipped_text sorted by length of each document
            invert_idxs: indices from the original zipped_text so that we can invert
                the list after prediction
        """
        lengths = [len(text["X"]) for text in zipped_text]
        sorted_idxs = np.argsort(lengths)
        sorted_text = [zipped_text[i] for i in sorted_idxs]
        invert_idxs = np.zeros(sorted_idxs.shape, dtype=int)
        invert_idxs[sorted_idxs] = np.arange(sorted_idxs.shape[0])
        return sorted_text, invert_idxs

    def _inference(
        self,
        zipped_data,
        context=None,
        update_hook=None,
        chunked_length=None,
    ) -> t.Union[List[Dict[str, np.ndarray]], t.Iterator[Dict[str, np.ndarray]]]:
        def get_zipped_data():
            return iter(zipped_data)

        input_fn = self.input_pipeline.get_dataset_from_generator(
            get_zipped_data, input_mode=InputMode.PREDICT, update_hook=update_hook
        )["predict_dataset"]

        model = self.model

        length = chunked_length if chunked_length is not None else len(zipped_data)

        progress = ProgressBar(total=length, desc="Inference", update_hook=update_hook)
        for batch in input_fn:
            preds = model.finetune_predict(batch)
            pred_numpy = {k: v.numpy() for k, v in preds.items()}
            batch_size = batch["tokens"].shape[0]
            # Items without a batch dim we include in all pred batches. In practice this is limited to just transition params
            # but we include the shape check just to prevent errors if anything else sneaks through.
            not_batched = {
                k
                for k, v in pred_numpy.items()
                if v.shape[0] != batch_size or k == "transition_params"
            }
            for i in range(batch_size):
                progress.update(i)
                step_value = {
                    k: pred_numpy[k] if k in not_batched else pred_numpy[k][i]
                    for k in pred_numpy
                }
                yield step_value

    def fit(self, *args, **kwargs):
        """An alias for finetune."""
        return self.finetune(*args, **kwargs)

    @abstractmethod
    def _predict(self, zipped_data, **kwargs):
        raise NotImplementedError()

    def predict(self, Xs, context=None, **kwargs):
        zipped_data = self.input_pipeline.zip_list_to_dict(X=Xs, context=context)

        if self.config.sort_by_length:
            zipped_data, invert_idxs = self._sort_by_length(zipped_data)

        outputs = self._predict(zipped_data, **kwargs)

        if self.config.sort_by_length:
            outputs = [outputs[i] for i in invert_idxs]

        return outputs

    def _predict_proba(self, zipped_data, **kwargs):
        """
        Produce raw numeric outputs for proba predictions
        """
        raise NotImplemented()

    def predict_proba(self, Xs, context=None, **kwargs):
        """
        The base method for predicting from the model.
        """
        zipped_data = self.input_pipeline.zip_list_to_dict(X=Xs, context=context)

        if self.config.sort_by_length:
            zipped_data, invert_idxs = self._sort_by_length(zipped_data)

        raw_probas = self._predict_proba(zipped_data)
        classes = self.input_pipeline.label_encoder.classes_

        formatted_predictions = []
        for probas in raw_probas:
            formatted_predictions.append(dict(zip(classes, probas.tolist())))
        if self.config.sort_by_length:
            formatted_predictions = [formatted_predictions[i] for i in invert_idxs]

        return formatted_predictions

    def featurize(self, Xs, context=None, **kwargs):
        """
        Base method to get raw features out of the model.
        These features are the same features that are fed into the target_model.
        """
        if self.config.chunk_long_sequences:
            warnings.warn(
                "`chunk_long_sequences` is currently not compatible with featurize_sequence"
            )
        zipped_data = self.input_pipeline.zip_list_to_dict(X=Xs, context=context)
        raw_preds = self._inference(zipped_data, **kwargs)
        raw_preds = [pred["features"] for pred in raw_preds]
        feats = np.asarray(raw_preds)
        return feats

    def featurize_sequence(self, Xs, context=None, **kwargs):
        """
        Base method to get raw token-level features out of the model.
        These features are the same features that are fed into the target_model.
        """
        zipped_data = self.input_pipeline.zip_list_to_dict(X=Xs, context=context)
        raw_preds = self._inference(zipped_data, **kwargs)
        raw_preds = [pred["sequence_features"] for pred in raw_preds]
        chunk_gens = [self.input_pipeline._text_to_ids(d["X"]) for d in zipped_data]

        chunks = []
        chunk_to_seq = []
        for i, gen in enumerate(chunk_gens):
            for chunk in gen:
                chunks.append(chunk)
                chunk_to_seq.append(i)

        processed_preds = [[] for _ in range(len(zipped_data))]
        for i, pred in enumerate(raw_preds):
            if self.config.chunk_long_sequences:
                start, end = chunks[i].useful_start, chunks[i].useful_end
            else:
                start, end = 0, None
            not_padding = np.array(chunks[i].token_ends[start:end]) != -1
            no_pad_pred = pred[start : start + len(not_padding)][not_padding]
            processed_preds[chunk_to_seq[i]].extend(no_pad_pred)

        processed_preds = [np.asarray(pred) for pred in processed_preds]
        return processed_preds

    def transform(self, *args, **kwargs):
        """
        An alias for `featurize`.
        """
        return self.featurize(*args, **kwargs)

    def _set_random_seed(self, seed=None):
        seed = seed or self.config.seed
        random.seed(seed)
        np.random.seed(seed)
        tf.compat.v1.set_random_seed(seed)

    @property
    def classes(self):
        return [
            class_name
            for class_name in self.input_pipeline.label_encoder.target_labels
            if class_name != self.config.pad_token
        ]

    def __getstate__(self):
        """
        Leave serialization of all tf objects to tf
        """
        required_fields = ["_load_from_file", "config", "input_pipeline", "_trained"]
        serialized_state = {
            k: v for k, v in self.__dict__.items() if k in required_fields
        }
        return serialized_state

    def save(self, path: str | pathlib.Path | io.BytesIO):
        """
        Saves the state of the model to disk to the folder specific by `path`.  If `path` does not exist, it will be auto-created.

        Save is performed in two steps:
            - Serialize tf graph to disk using tf.Saver
            - Serialize python model using pickle

        Note:
            Does not serialize state of Adam optimizer.
            Should not be used to save / restore a training model.
        """
        if path is None:
            return

        if isinstance(path, pathlib.Path):
            path = str(path)
        if isinstance(path, str):
            path = os.path.abspath(path)
        if self._model is None:
            if self.saver.variables:
                self.model  # trigger reinitialization of the model only if there is custom state.
            else:
                raise ValueError("Model has not been initialized. Call fit() first.")
        self.saver.save_model(model=self._model, finetune_obj=self, path=path)

    @classmethod
    def save_multiple(cls, path: str, models: Mapping[str, "BaseModel"]):
        def save_to_bytes(model, k):
            f = io.BytesIO()
            if isinstance(model, BaseModel):
                model.save(f)
            elif hasattr(model, "read"):
                f = model
            else:
                joblib.dump(model, f)
                k = "__non_model__" + k
            f.seek(0)
            return k, f.read()

        joblib.dump(dict(save_to_bytes(model, k) for k, model in models.items()), path)

    def create_base_model(self, filename, exists_ok=False):
        """
        Saves the current weights into the correct file format to be used as a base model.
        :param filename: the path to save the base model relative to finetune's base model filestore.
        :param exists_ok: Whether to replace the model if it exists.
        """
        base_model_path = os.path.join(os.path.dirname(__file__), "model", filename)

        if not exists_ok and os.path.exists(base_model_path):
            base_model_path = base_model_path + str(int(time.time()))
            LOGGER.warning(
                "Cannot overwrite model {}, set exists_ok to overwrite, saving as {} to avoid loss of data.".format(
                    filename, base_model_path
                )
            )

        if not self.saver.variables:
            raise FinetuneError(
                "Cannot save a base model with no weights changed. Call fit before creating a base model."
            )
        weights_stripped = {
            k: v
            for k, v in self.saver.variables.items()
            if "featurizer" in k and "Adam" not in k
        }
        joblib.dump(weights_stripped, base_model_path)

    def load(path: str | pathlib.Path | io.BytesIO, *args, key=None, **kwargs):
        """
        Load a saved fine-tuned model from disk.  Path provided should be a folder which contains .pkl and tf.Saver() files

        :param path: string path name to load model from.  Same value as previously provided to :meth:`save`. Must be a folder.
        :param **kwargs: key-value pairs of config items to override.
        """
        if not isinstance(path, (str, pathlib.Path, io.BytesIO)) and not hasattr(
            path, "write"
        ):
            instance = path
            raise FinetuneError(
                'The .load() method can only be called on the class, not on an instance. Try `{}.load("{}") instead.'.format(
                    instance.__class__.__name__, args[0]
                )
            )

        if key is not None:
            model_package = joblib.load(path)
            if key not in model_package:
                nm_key = "__non_model__" + key
                if nm_key in model_package:
                    return joblib.load(io.BytesIO(model_package[nm_key]))
                else:
                    raise ValueError("Key {} not found in file".format(key))
            path = io.BytesIO(model_package[key])
            del model_package

        assert_valid_config(**kwargs)

        saver = Saver()
        model = saver.load(path)

        default_config = get_default_config()

        # Backwards compatability
        # Ensure old models get new default settings
        for setting, default in default_config.items():
            if not hasattr(model.config, setting):
                if setting == "add_eos_bos_to_chunk":
                    model.config.add_eos_bos_to_chunk = False
                else:
                    model.config.update({setting: default})

        model.config.update(kwargs)
        for setting in list(model.config.keys()):
            if setting not in default_config:
                LOGGER.warning(
                    "The config value {} is no longer supported".format(setting)
                )
                del model.config[setting]
        model.config_overrides = model.config
        model.config = model.resolve_config()
        if (
            model.config.version == "0.8.6"
            and model.config.base_model.encoder == RoBERTaEncoderV2
        ):
            # In version 0.8.6 collapse whitespace was broken
            model.config.collapse_whitespace = False

        model.input_pipeline.config = model.config
        download_data_if_required(model.config.base_model)
        saver.set_fallback(model.config.base_model_path)
        model._initialize()
        model.saver.variables = saver.variables
        model._trained = True
        model.check_gpu_for_fp16()
        return model

    def process_long_sequence(self, zipped_data):
        # outputs predictions for each chunk of each document.
        pred_iterator = self._inference(
            zipped_data,
            chunked_length=0,
        )

        # Outputs (probably chunked) Encoded outputs for each document
        chunk_generator = (
            self.input_pipeline._text_to_ids(d["X"]) for d in zipped_data
        )

        # outputs flattened chunk by chunk tokenized outputs
        # along with booleans for the start and end of documents.
        chunk_alignment_iterator = (
            (sample, is_start, is_end)
            for ae in chunk_generator
            for sample, is_start, is_end in start_end_gen(ae)
        )

        # By using iterators it means that we can handle prediction
        # and output processing doc by doc reducing the memory consumption
        # compared to having to hold the tokenized input and per-token
        # probabilities for the whole dataset.
        for pred, (arr_enc, start_of_doc, end_of_doc) in zip(
            pred_iterator, chunk_alignment_iterator
        ):
            token_end_idx = arr_enc.token_ends
            token_start_idx = arr_enc.token_starts
            useful_start = arr_enc.useful_start
            useful_end = arr_enc.useful_end
            yield {
                "token_start_idx": token_start_idx,
                "token_end_idx": token_end_idx,
                "start_of_doc": start_of_doc,
                "end_of_doc": end_of_doc,
                "useful_start": useful_start,
                "useful_end": useful_end,
                **pred,  # Preds and probas
            }

    def close(self, update_saver=True):
        if update_saver and self._model:
            self.saver.update_variables(self._model)
        del self._model
        self._model = None
        self.input_pipeline._batch_postprocessor = (
            self.input_pipeline.MISSING_BATCH_POSTPROCESSOR
        )
        self.input_pipeline._text_encoder = None
